"""Milvus collection setup + data insertion.

Creates the student_results and faq collections, inserts all chunks with
dense embeddings. BM25 sparse vectors are auto-generated by Milvus.

Usage:
    cd backend
    python -m ingestion.milvus_indexer
"""

import json
import time
from pathlib import Path

from pymilvus import DataType, Function, FunctionType, MilvusClient

from config import settings

GREEN = "\033[92m"
RED = "\033[91m"
YELLOW = "\033[93m"
RESET = "\033[0m"

BATCH_SIZE = 500
MAX_RETRIES = 3


def _connect(retry: int = MAX_RETRIES) -> MilvusClient:
    """Connect to Milvus with retry logic."""
    backoff = 2
    for attempt in range(retry):
        try:
            client = MilvusClient(uri=f"http://{settings.MILVUS_HOST}:{settings.MILVUS_PORT}")
            # Quick sanity check — list collections
            client.list_collections()
            return client
        except Exception as exc:
            if attempt == retry - 1:
                raise RuntimeError(f"Cannot connect to Milvus after {retry} attempts: {exc}") from exc
            print(f"{YELLOW}  Milvus not ready, retry {attempt + 1}/{retry} (waiting {backoff}s)...{RESET}")
            time.sleep(backoff)
            backoff *= 2
    raise RuntimeError("unreachable")


def create_student_results_collection(client: MilvusClient) -> None:
    """Create the student_results collection with HNSW + BM25 indexes."""
    collection = settings.MILVUS_COLLECTION

    if client.has_collection(collection):
        client.drop_collection(collection)
        print(f"  Dropped existing '{collection}' collection")

    schema = client.create_schema(auto_id=False)

    # Primary key
    schema.add_field("chunk_id", DataType.VARCHAR, is_primary=True, max_length=100)

    # Text field — BM25 tokenisation enabled
    schema.add_field("text", DataType.VARCHAR, max_length=10000, enable_analyzer=True)

    # Dense vector from nomic-embed-text
    schema.add_field("dense", DataType.FLOAT_VECTOR, dim=settings.OLLAMA_EMBED_DIM)

    # Sparse vector — auto-generated by BM25 function
    schema.add_field("sparse", DataType.SPARSE_FLOAT_VECTOR)

    # Metadata fields
    schema.add_field("roll_no", DataType.VARCHAR, max_length=50)
    schema.add_field("name", DataType.VARCHAR, max_length=255)
    schema.add_field("branch", DataType.VARCHAR, max_length=300)
    schema.add_field("course", DataType.VARCHAR, max_length=100)
    schema.add_field("semester", DataType.INT64)
    schema.add_field("sgpa", DataType.FLOAT)
    schema.add_field("session", DataType.VARCHAR, max_length=100)
    schema.add_field("result_status", DataType.VARCHAR, max_length=50)
    schema.add_field("gender", DataType.VARCHAR, max_length=5)

    # BM25 function: auto-converts text → sparse vectors
    schema.add_function(Function(
        name="bm25_fn",
        function_type=FunctionType.BM25,
        input_field_names=["text"],
        output_field_names=["sparse"],
    ))

    # Index configuration
    index_params = client.prepare_index_params()

    # Dense: HNSW for fast ANN search
    index_params.add_index(
        field_name="dense",
        index_type="HNSW",
        metric_type="COSINE",
        params={"M": 32, "efConstruction": 200},
    )

    # Sparse: inverted index for BM25
    index_params.add_index(
        field_name="sparse",
        index_type="SPARSE_INVERTED_INDEX",
        metric_type="BM25",
    )

    client.create_collection(
        collection_name=collection,
        schema=schema,
        index_params=index_params,
    )

    print(f"{GREEN}✓ Created collection '{collection}' with HNSW + BM25 indexes{RESET}")


def create_faq_collection(client: MilvusClient) -> None:
    """Create the empty FAQ collection for later use."""
    faq_collection = settings.MILVUS_FAQ_COLLECTION

    if client.has_collection(faq_collection):
        client.drop_collection(faq_collection)

    schema = client.create_schema(auto_id=False)
    schema.add_field("faq_id", DataType.VARCHAR, is_primary=True, max_length=100)
    schema.add_field("question", DataType.VARCHAR, max_length=3000, enable_analyzer=True)
    schema.add_field("answer", DataType.VARCHAR, max_length=10000)
    schema.add_field("dense", DataType.FLOAT_VECTOR, dim=settings.OLLAMA_EMBED_DIM)
    schema.add_field("sparse", DataType.SPARSE_FLOAT_VECTOR)

    schema.add_function(Function(
        name="faq_bm25",
        function_type=FunctionType.BM25,
        input_field_names=["question"],
        output_field_names=["sparse"],
    ))

    index_params = client.prepare_index_params()
    index_params.add_index(
        field_name="dense",
        index_type="HNSW",
        metric_type="COSINE",
        params={"M": 16, "efConstruction": 100},
    )
    index_params.add_index(
        field_name="sparse",
        index_type="SPARSE_INVERTED_INDEX",
        metric_type="BM25",
    )

    client.create_collection(
        collection_name=faq_collection,
        schema=schema,
        index_params=index_params,
    )

    print(f"{GREEN}✓ Created empty '{faq_collection}' collection{RESET}")


def insert_data(client: MilvusClient) -> int:
    """Load chunks + embeddings from data/ and insert into Milvus.

    Returns:
        Total number of inserted entities.
    """
    collection = settings.MILVUS_COLLECTION
    chunks_path = settings.db_path("data/chunks.jsonl")
    embeddings_path = settings.db_path("data/embeddings.jsonl")

    # Load chunks
    chunks: dict[str, dict] = {}
    with open(chunks_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            obj = json.loads(line)
            cid = obj["metadata"]["chunk_id"]
            chunks[cid] = obj

    # Load embeddings
    embeddings: dict[str, list[float]] = {}
    with open(embeddings_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            obj = json.loads(line)
            embeddings[obj["chunk_id"]] = obj["embedding"]

    # Build insertion records (order by chunk_id)
    records: list[dict] = []
    for cid, chunk in chunks.items():
        if cid not in embeddings:
            print(f"{YELLOW}  Warning: no embedding for {cid}, skipping{RESET}")
            continue

        meta = chunk["metadata"]
        # NOTE: do NOT include 'sparse' — Milvus auto-generates it from text via BM25 function
        records.append({
            "chunk_id": cid,
            "text": chunk["text"],
            "dense": embeddings[cid],
            "roll_no": meta["roll_no"],
            "name": meta["name"],
            "branch": meta["branch"],
            "course": meta["course"],
            "semester": int(meta["semester"]),
            "sgpa": float(meta["sgpa"]),
            "session": meta["session"],
            "result_status": meta["result_status"],
            "gender": meta["gender"],
        })

    total = len(records)
    print(f"  Inserting {total} chunks into '{collection}'...")

    # Insert in batches
    for i in range(0, total, BATCH_SIZE):
        batch = records[i : i + BATCH_SIZE]
        client.insert(collection, batch)
        inserted = min(i + BATCH_SIZE, total)
        print(f"  Inserted {inserted}/{total} chunks...")

    return total


def run_indexer() -> None:
    """Full Milvus indexing pipeline."""
    print(f"{YELLOW}Starting Milvus indexing...{RESET}")

    client = _connect()
    create_student_results_collection(client)
    total = insert_data(client)
    create_faq_collection(client)

    print(f"\n{GREEN}✓ Milvus indexing complete. Total chunks: {total}{RESET}")


if __name__ == "__main__":
    run_indexer()
